language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - echo "www.vicicode.com" > CNAME
  - cp ../404.html .
  - git init
  - git config user.name "Silent Yang"
  - git config user.email "568875138@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hexo

env:
 global:
   - GH_REF: github.com/568875138/568875138.github.io.git